### ISSUE TITLE
Rinkeby Honeyswap doesn't work and it's need to really test Gardens

### ISSUE THREAD

**Issue by GriffGreen** [1Hive/honeyswap#95] opened 2021-06-14 16:13 UTC
**Describe the bug**

Honeyswap on rinkeby doesnt work!

**To Reproduce**
1. Go to honeyswap with your browser set to rinkeby
2. Leave the first token set to ETH and click on the token to swap
3. Add "0xd8d67562307d18fa6c052092da5dc18fc6b13809" (the GIV token)
4. Type something into the ETH field
5. See error

**Expected behavior**
I want to swap Rinkeby ETH for GIV tokens to change the exchange rate and see how that effects proposals deposits and challenge deposits to the Gardens... 

I also want HNYT!!! 

**Screenshots**

![Screen Shot 2021-06-14 at 7 21 26 AM](https://user-images.githubusercontent.com/14945613/121924326-1640a800-cd3c-11eb-962b-804dc288f180.png)
![Screen Shot 2021-06-14 at 7 20 26 AM](https://user-images.githubusercontent.com/14945613/121924340-193b9880-cd3c-11eb-803d-be9ff990927b.png)

**Comment by onbjerg** [comment] 2021-06-20 15:38
I'm going to look into this - I know what the issue is, but I need to seek some information before I can fix it. Hang tight!

**Comment by onbjerg** [comment] 2021-06-20 20:26
Okay, so I asked Will and we don't have a Honeyswap deployment on Rinkeby - we usually just use the Uniswap Rinkeby deployment available on the standard Uniswap interface at https://app.uniswap.org/

If you want, I can hook up the Honeyswap frontend to Rinkeby Uniswap but it would require that the front-end be run locally since it wouldn't make much sense for us to have Rinkeby in our user facing deployment. For now, I'm going to close the issue. Feel free to reopen it :blush: :+1:

**Closed as completed by onbjerg** 2021-06-20 20:26 UTC
Labels: bug, Frontend, priority: medium
